export async function dispatchReadOnly({ command, client, emit, application, identity, handlers }) {
  const calls = {
    health: () => handlers.health({ client, emit }),
    ready: () => handlers.ready({ client, emit }),
    'initialization-status': () => handlers.initializationStatus({ client, emit }),
    'initialization-verify': () => handlers.initializationVerify({ client, emit }),
    'initialization-plan': () => handlers.initializationPlan({ client, emit }),
    telemetry: () => handlers.telemetry({ client, emit }),
    'telemetry-detail': () => handlers.telemetryDetail({ client, emit, application }),
    connections: () => handlers.connections({ client, emit, application }),
    status: () => handlers.clusterStatus({ client, emit }),
    'cluster-status': () => handlers.clusterStatus({ client, emit }),
    'cluster-observations': () => handlers.clusterObservations({ client, emit }),
    'node-evidence': () => handlers.nodeEvidence({ client, emit }),
    'cluster-quorum': () => handlers.clusterQuorum({ client, emit }),
    'assignment-status': () => handlers.assignment({ client, emit, application, identity }),
    'bundle-version': () => handlers.bundleVersion({ client, emit, application, identity }),
    routes: () => handlers.routes({ client, emit, application }),
    bundle: () => handlers.bundle({ client, emit, application, identity }),
    'routing-resync': () => handlers.resync({ client, emit, application }),
    'config-inspect': () => handlers.configInspect({ client, emit }),
    'config-verify': () => handlers.configVerify({ client, emit }),
    'metadata-status': () => handlers.metadataStatus({ client, emit }),
    'metadata-verify': () => handlers.metadataVerify({ client, emit }),
    'database-list': () => handlers.databaseList({ client, emit }),
    'identity-list': () => handlers.identityList({ client, emit, application }),
    'account-list': () => handlers.accountList({ client, emit }),
    'token-list': () => handlers.tokenList({ client, emit }),
    'recovery-status': () => handlers.recoveryStatus({ client, emit }),
    'recovery-events': () => handlers.recoveryEvents({ client, emit }),
    'cold-recovery-evidence': () => handlers.coldRecoveryEvidence({ client, emit }),
    'cold-recovery-status': () => handlers.coldRecoveryStatus({ client, emit }),
    'cold-recovery-plan': () => handlers.coldRecoveryPlan({ client, emit }),
    'routing-validate': () => handlers.routingValidate({ client, emit, application }),
    'routing-events': () => handlers.routingEvents({ client, emit, application }),
    'routing-watch': () => handlers.routingWatch({ client, emit, application }),
    'telemetry-watch': () => handlers.telemetryWatch({ client, emit, application }),
  };
  return calls[command] ? calls[command]() : undefined;
}
