import { appendFile, readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createGunzip } from 'node:zlib';
import { pipeline } from 'node:stream/promises';
import { createReadStream } from 'node:fs';
import { mysqlArgs, validateDatabaseName } from '../database/commands.mjs';

export function runRestore(binary, args, input) { return new Promise((resolve, reject) => { const child = spawn(binary, args, { shell: false, stdio: ['pipe', 'ignore', 'pipe'] }); let stderr = ''; child.stderr.setEncoding('utf8'); child.stderr.on('data', (chunk) => { stderr += chunk; }); pipeline(input, child.stdin).catch(reject); child.once('error', reject); child.once('close', (code) => code === 0 ? resolve() : reject(new Error(stderr.trim() || `restore exited with ${code}`))); }); }
export function runSql(binary, args) { return new Promise((resolve, reject) => { const child = spawn(binary, args, { shell: false, stdio: ['ignore', 'ignore', 'pipe'] }); let stderr = ''; child.stderr.setEncoding('utf8'); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.once('error', reject); child.once('close', (code) => code === 0 ? resolve() : reject(new Error(stderr.trim() || `sql exited with ${code}`))); }); }
export async function restoreVerify({ restoreRoot, credentialsFile, host = 'localhost', mysql = 'mariadb', prefix = 'restore_verify_', logPath, execSql = runSql, restore = runRestore, read = readFile, writeLog = appendFile, stream = createReadStream, notify = async () => {}, now = () => new Date().toISOString() }) { if (logPath) await writeLog(logPath, `restore verification started ${now()}\n`); let currentDatabase; try { const names = (await read(`${restoreRoot}/DATABASES`, 'utf8')).split(/\r?\n/).filter(Boolean); let count = 0; for (const database of names) { currentDatabase = database; if (['sys', 'mysql'].includes(database)) continue; validateDatabaseName(database); const target = `${prefix}${database}`; try { await execSql(mysql, [...mysqlArgs(credentialsFile, host), '-e', `DROP DATABASE IF EXISTS \`${target}\`; CREATE DATABASE \`${target}\`;`]); await restore(mysql, [...mysqlArgs(credentialsFile, host), target], stream(`${restoreRoot}/${database}.sql.gz`).pipe(createGunzip())); } finally { await execSql(mysql, [...mysqlArgs(credentialsFile, host), '-e', `DROP DATABASE IF EXISTS \`${target}\`;`]); } count += 1; } if (logPath) await writeLog(logPath, `restore verification passed: ${count} application schemas ${now()}\n`); return count; } catch (error) { const message = `restore verification failed${currentDatabase ? ` for ${currentDatabase}` : ''}: ${error instanceof Error ? error.message : String(error)}`; if (logPath) await writeLog(logPath, `${message} ${now()}\n`); await notify(message); throw error; } }
